using Test

@testset "RDF.jl" begin
    include("test_iris.jl")
    include("test_literals.jl")
    include("test_blank_nodes.jl")
    include("test_triples.jl")
    include("test_graphs.jl")
    include("test_datasets.jl")
    include("test_namespaces.jl")
    include("test_pattern_matching.jl")
    include("test_serialization.jl")
    include("test_inference.jl")
    include("test_validation.jl")
    include("test_errors.jl")
    include("test_tables.jl")
    include("test_type_stability.jl")
    include("w3c/w3c_tests.jl")
    include("test_w3c_turtle.jl")
    include("test_w3c_sparql.jl")
    include("test_sparql_results.jl")
    include("test_w3c_ntriples.jl")
    include("test_w3c_nquads.jl")
    include("test_w3c_isomorphism.jl")
    include("test_jsonld.jl")
    include("test_aqua.jl")
end
