module dcterms

using ..RDF: IRI

const _BASE = "http://purl.org/dc/terms/"

const abstract_       = IRI(_BASE * "abstract")
const accessRights    = IRI(_BASE * "accessRights")
const accrualMethod   = IRI(_BASE * "accrualMethod")
const accrualPeriodicity = IRI(_BASE * "accrualPeriodicity")
const accrualPolicy   = IRI(_BASE * "accrualPolicy")
const alternative     = IRI(_BASE * "alternative")
const audience        = IRI(_BASE * "audience")
const available       = IRI(_BASE * "available")
const bibliographicCitation = IRI(_BASE * "bibliographicCitation")
const conformsTo      = IRI(_BASE * "conformsTo")
const contributor     = IRI(_BASE * "contributor")
const coverage        = IRI(_BASE * "coverage")
const created         = IRI(_BASE * "created")
const creator         = IRI(_BASE * "creator")
const date            = IRI(_BASE * "date")
const dateAccepted    = IRI(_BASE * "dateAccepted")
const dateCopyrighted = IRI(_BASE * "dateCopyrighted")
const dateSubmitted   = IRI(_BASE * "dateSubmitted")
const description     = IRI(_BASE * "description")
const educationLevel  = IRI(_BASE * "educationLevel")
const extent          = IRI(_BASE * "extent")
const format          = IRI(_BASE * "format")
const hasFormat       = IRI(_BASE * "hasFormat")
const hasPart         = IRI(_BASE * "hasPart")
const hasVersion      = IRI(_BASE * "hasVersion")
const identifier      = IRI(_BASE * "identifier")
const instructionalMethod = IRI(_BASE * "instructionalMethod")
const isFormatOf      = IRI(_BASE * "isFormatOf")
const isPartOf        = IRI(_BASE * "isPartOf")
const isReferencedBy  = IRI(_BASE * "isReferencedBy")
const isReplacedBy    = IRI(_BASE * "isReplacedBy")
const isRequiredBy    = IRI(_BASE * "isRequiredBy")
const isVersionOf     = IRI(_BASE * "isVersionOf")
const issued          = IRI(_BASE * "issued")
const language        = IRI(_BASE * "language")
const license         = IRI(_BASE * "license")
const mediator        = IRI(_BASE * "mediator")
const medium          = IRI(_BASE * "medium")
const modified        = IRI(_BASE * "modified")
const provenance      = IRI(_BASE * "provenance")
const publisher       = IRI(_BASE * "publisher")
const references      = IRI(_BASE * "references")
const relation        = IRI(_BASE * "relation")
const replaces        = IRI(_BASE * "replaces")
const requires        = IRI(_BASE * "requires")
const rights          = IRI(_BASE * "rights")
const rightsHolder    = IRI(_BASE * "rightsHolder")
const source          = IRI(_BASE * "source")
const spatial         = IRI(_BASE * "spatial")
const subject         = IRI(_BASE * "subject")
const tableOfContents = IRI(_BASE * "tableOfContents")
const temporal        = IRI(_BASE * "temporal")
const title           = IRI(_BASE * "title")
const type            = IRI(_BASE * "type")
const valid           = IRI(_BASE * "valid")

end # module dcterms
