module foaf

using ..RDF: IRI

const _BASE = "http://xmlns.com/foaf/0.1/"

const Agent           = IRI(_BASE * "Agent")
const Person          = IRI(_BASE * "Person")
const Organization    = IRI(_BASE * "Organization")
const Group           = IRI(_BASE * "Group")
const Document        = IRI(_BASE * "Document")
const Image           = IRI(_BASE * "Image")
const Project         = IRI(_BASE * "Project")
const OnlineAccount   = IRI(_BASE * "OnlineAccount")
const PersonalProfileDocument = IRI(_BASE * "PersonalProfileDocument")

const name            = IRI(_BASE * "name")
const title           = IRI(_BASE * "title")
const givenName       = IRI(_BASE * "givenName")
const familyName      = IRI(_BASE * "familyName")
const nick            = IRI(_BASE * "nick")
const mbox            = IRI(_BASE * "mbox")
const mbox_sha1sum    = IRI(_BASE * "mbox_sha1sum")
const homepage        = IRI(_BASE * "homepage")
const weblog          = IRI(_BASE * "weblog")
const openid          = IRI(_BASE * "openid")
const jabberID        = IRI(_BASE * "jabberID")
const knows           = IRI(_BASE * "knows")
const member          = IRI(_BASE * "member")
const based_near      = IRI(_BASE * "based_near")
const age             = IRI(_BASE * "age")
const gender          = IRI(_BASE * "gender")
const birthday        = IRI(_BASE * "birthday")
const made            = IRI(_BASE * "made")
const maker           = IRI(_BASE * "maker")
const primaryTopic    = IRI(_BASE * "primaryTopic")
const isPrimaryTopicOf = IRI(_BASE * "isPrimaryTopicOf")
const topic           = IRI(_BASE * "topic")
const page            = IRI(_BASE * "page")
const depiction       = IRI(_BASE * "depiction")
const depicts         = IRI(_BASE * "depicts")
const thumbnail       = IRI(_BASE * "thumbnail")
const logo            = IRI(_BASE * "logo")
const phone           = IRI(_BASE * "phone")
const workplaceHomepage = IRI(_BASE * "workplaceHomepage")
const workInfoHomepage = IRI(_BASE * "workInfoHomepage")
const schoolHomepage  = IRI(_BASE * "schoolHomepage")
const account         = IRI(_BASE * "account")
const accountName     = IRI(_BASE * "accountName")
const accountServiceHomepage = IRI(_BASE * "accountServiceHomepage")
const currentProject  = IRI(_BASE * "currentProject")
const pastProject     = IRI(_BASE * "pastProject")
const interest        = IRI(_BASE * "interest")
const topic_interest  = IRI(_BASE * "topic_interest")
const publications    = IRI(_BASE * "publications")
const geekcode        = IRI(_BASE * "geekcode")
const myersBriggs     = IRI(_BASE * "myersBriggs")
const dnaChecksum     = IRI(_BASE * "dnaChecksum")

end # module foaf
