module schema

using ..RDF: IRI

const _BASE = "https://schema.org/"

# Classes
const Thing           = IRI(_BASE * "Thing")
const Person          = IRI(_BASE * "Person")
const Organization    = IRI(_BASE * "Organization")
const Place           = IRI(_BASE * "Place")
const Event           = IRI(_BASE * "Event")
const CreativeWork    = IRI(_BASE * "CreativeWork")
const Article         = IRI(_BASE * "Article")
const Book            = IRI(_BASE * "Book")
const Movie           = IRI(_BASE * "Movie")
const MusicRecording  = IRI(_BASE * "MusicRecording")
const Product         = IRI(_BASE * "Product")
const Offer           = IRI(_BASE * "Offer")
const Action          = IRI(_BASE * "Action")
const ImageObject     = IRI(_BASE * "ImageObject")
const VideoObject     = IRI(_BASE * "VideoObject")
const DataFeed        = IRI(_BASE * "DataFeed")
const Dataset         = IRI(_BASE * "Dataset")

# Properties
const name            = IRI(_BASE * "name")
const description     = IRI(_BASE * "description")
const url             = IRI(_BASE * "url")
const image           = IRI(_BASE * "image")
const identifier      = IRI(_BASE * "identifier")
const sameAs          = IRI(_BASE * "sameAs")
const additionalType  = IRI(_BASE * "additionalType")
const alternateName   = IRI(_BASE * "alternateName")
const disambiguatingDescription = IRI(_BASE * "disambiguatingDescription")
const subjectOf       = IRI(_BASE * "subjectOf")
const mainEntityOfPage = IRI(_BASE * "mainEntityOfPage")
const potentialAction = IRI(_BASE * "potentialAction")
const givenName       = IRI(_BASE * "givenName")
const familyName      = IRI(_BASE * "familyName")
const email           = IRI(_BASE * "email")
const telephone       = IRI(_BASE * "telephone")
const birthDate       = IRI(_BASE * "birthDate")
const deathDate       = IRI(_BASE * "deathDate")
const nationality     = IRI(_BASE * "nationality")
const gender          = IRI(_BASE * "gender")
const jobTitle        = IRI(_BASE * "jobTitle")
const worksFor        = IRI(_BASE * "worksFor")
const knows           = IRI(_BASE * "knows")
const address         = IRI(_BASE * "address")
const member          = IRI(_BASE * "member")
const founder         = IRI(_BASE * "founder")
const employee        = IRI(_BASE * "employee")
const dateCreated     = IRI(_BASE * "dateCreated")
const dateModified    = IRI(_BASE * "dateModified")
const datePublished   = IRI(_BASE * "datePublished")
const author          = IRI(_BASE * "author")
const publisher       = IRI(_BASE * "publisher")
const license         = IRI(_BASE * "license")
const version_        = IRI(_BASE * "version")
const keywords        = IRI(_BASE * "keywords")
const about           = IRI(_BASE * "about")
const price           = IRI(_BASE * "price")
const priceCurrency   = IRI(_BASE * "priceCurrency")
const availability    = IRI(_BASE * "availability")

end # module schema
